### ISSUE TITLE
[QUESTION] Should the type of `return_void` be void?

### ISSUE THREAD

**Issue by yanang007** [roger-dv/cpp20-coro-generator#1]
Hi! Really awesome implementation! 
But I encountered an error `The type of a coroutine promise return_value or return_void expression must be void` when experimenting in Visual Studio 2022 (which I believe is MSVC 17) and it seems that MSVC is true according to some clarification ([N4868](https://timsong-cpp.github.io/cppwp/stmt.return.coroutine#2), [Microsoft DevBlogs](https://devblogs.microsoft.com/oldnewthing/20210330-00/?p=105019) and [cppref](https://en.cppreference.com/w/cpp/language/coroutines)).

Let's start with a simplified code that does compile and run as expected in MSVC.
```
coro::generator<char> producer()
{
    const char x[] = "11223345";
    for (auto c : x) {
        co_yield c;
    }
}

int main()
{
    std::ranges::copy(producer(), std::ostream_iterator<char>(std::cout));
}
```
However, a modified version with a conditional `co_return` to terminate the coroutine will produce an error C7625 `The type of a coroutine promise return_value or return_void expression must be void`.
```
coro::generator<char> producer()
{
    const char x[] = "11223345";
    for (auto c : x) {
        if (c > '2') co_return;
        co_yield c;
    }
}

int main()
{
    std::ranges::copy(producer(), std::ostream_iterator<char>(std::cout));
}
```

This can be fixed by simply modifying following lines
https://github.com/roger-dv/cpp20-coro-generator/blob/a15eb0fdf72ab26a04bba7532953475b9c3f0b8e/generator.h#L118-L120
into
```
    void return_void() {}
```
And the modified version has been **tested** in **GCC 12.1.0** and **Clang 15.0.7**.

As is stated in [n4868](https://timsong-cpp.github.io/cppwp/n4868/stmt.return.coroutine#2), and in other exmples([Microsoft DevBlogs](https://devblogs.microsoft.com/oldnewthing/20210330-00/?p=105019), [cppref](https://en.cppreference.com/w/cpp/language/coroutines)), it seems that the type of `return_void` and `return_value` should probably be void.

> [(2.1)](https://timsong-cpp.github.io/cppwp/n4868/stmt.return.coroutine#2.1) If the operand is a [braced-init-list](https://timsong-cpp.github.io/cppwp/n4868/dcl.init#nt:braced-init-list) or an expression of non-void type, S is p.return_­value([expr-or-braced-init-list](https://timsong-cpp.github.io/cppwp/n4868/dcl.init#nt:expr-or-braced-init-list)). The expression S shall be a prvalue of type void.
> [(2.2)](https://timsong-cpp.github.io/cppwp/n4868/stmt.return.coroutine#2.2) Otherwise, S is the [compound-statement](https://timsong-cpp.github.io/cppwp/n4868/stmt.block#nt:compound-statement) { [expression](https://timsong-cpp.github.io/cppwp/n4868/expr.comma#nt:expression)_opt ; p.return_­void(); }. The expression p.return_­void() shall be a prvalue of type void.

**Comment by roger-dv** [comment]
Gee, thanks for that feedback - I have made the suggested correction to
return_void().

The prior implementation was a hold-over from  Rainer Grimm's Concurrency
with Modern C++ example which used an experimental clang coroutine
implementation.

There is another issue that has been bothering me which is the dynamic
linking runtime error that happens with clang 16 builds where try to use
libc++. The current fix is to go ahead and use libstdc++ instead.

This started happening when I introduced the use of the std::pmr memory
management stuff. Before that, the clang 16 build worked fine with libc++.

So if anyone has any thoughts about that, am most interested to know.

Regards,
--RogerV

**Comment by yanang007** [comment]
Wow, thanks for your quick response!
Unfortunately I have no clue on the link issue ; (. As far as I know, although `pmr` (or P0220R1) is a C++17 feature, its support hasn't been implemented until libc++ 16.

**Comment by roger-dv** [comment]
Solved the clang/llvm libc++ issue - turned out to be a face-palm kind of problem. When I installed clang/llvm version 16 from a .tar.gz download, I failed to update the symbolic link `/lib/x86_64-linux-gnu/libc++.so.1.0` to refer to the version 16 libc++ shared library.

Oh, and these are the three x86_64 clang C++ shared libraries that need to be addressed:

```
-rw-r--r-- 1 root root  364432 Mar 18 17:49 /usr/local/clang-16.0.0/lib/x86_64-unknown-linux-gnu/libc++abi.so.1.0
-rw-r--r-- 1 root root 1267840 Mar 18 17:50 /usr/local/clang-16.0.0/lib/x86_64-unknown-linux-gnu/libc++.so.1.0
-rw-r--r-- 1 root root   61384 Mar 18 17:49 /usr/local/clang-16.0.0/lib/x86_64-unknown-linux-gnu/libunwind.so.1.0
```
Which for my install these three symbolic links needed to be revised to refer to version 16 (they had been referring to version 14):
```
/lib/x86_64-linux-gnu/libc++abi.so.1.0
/lib/x86_64-linux-gnu/libc++.so.1.0
/lib/x86_64-linux-gnu/libunwind.so.1.0
```
Here's `ldd` tool dump of this `coroutines` program as built with clang where see all three of these clang++ shared libs being referenced:
```
$ ldd Release/coroutines 
	linux-vdso.so.1 (0x00007ffd95112000)
	libc++.so.1 => /lib/x86_64-linux-gnu/libc++.so.1 (0x00007efd2f000000)
	libc++abi.so.1 => /lib/x86_64-linux-gnu/libc++abi.so.1 (0x00007efd2f42e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efd2f347000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efd2f327000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efd2edd8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efd2f320000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007efd2f31b000)
	libatomic.so.1 => /lib/x86_64-linux-gnu/libatomic.so.1 (0x00007efd2f311000)
	libunwind.so.1 => /lib/x86_64-linux-gnu/libunwind.so.1 (0x00007efd2f306000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efd2f496000)
```

**Comment by yanang007** [comment]
Lol, glad to hear that all the issues are solved. I think it's safe to close the issue now :) .
